### ISSUE TITLE
Question about W_I and W_F 

### ISSUE THREAD

**Issue by sdjsngs** [nguyetn89/anomaly_ICCV2019#2]
Hi ,  i am  re-implement your paper in pytorch and has some question about  W_i and W_f , in section 3.5 of  your paper , the weight is obtained on the training data?  
For Avenue dataset,  when  training is done (i.e. 15 epochs),   you  test  the 16  training clips on G model  through the 15 epoch's checkpoint to get the  out_appe and out_flow , then to get  the weight_I and weight_F in these 16 clips on average?   
thank you !!!

**Comment by nguyetn89** [comment]
Hi, yes! On that way, each weight indicates the impact of its partial score in the combination. The weight is defined as the inverse of the (average) score under the perspective that the lower score should give the higher impact (because the training data contain only frames of normality), and vice versa.
