### ISSUE TITLE
Optical flow computation

### ISSUE THREAD

**Issue by mohamedabdelhakem1** [nguyetn89/anomaly_ICCV2019#3]
I am reimplementing the paper for educational purposes, I am asking How much is the estimated size of the computed optical flow of datasets using FlowNet2-PyTorch to decide what to do with my Google Colab resources or Compute the optical flow ON THE FLY. Thanks in advance

**Comment by nguyetn89** [comment]
Hi, the input size of FlowNet2 was about (3x128, 3x192) and the output was then down-scaled 3 times to be (128, 192).

I used (128, 192) to reduce the computational cost for my available resources, but this size is too small for FlowNet2. That is why I up-scaled the frames and then down-scaled the results. I suggest to calculate the optical flow by FlowNet2 first, then store the results for further processing instead of repeating the on-the-fly calculation. Notice that the values (i.e. _xy_ displacement) of obtained optical flow was still up-scaled 3 times and I did not down-scale, but it should not affect the further processing.

I adapted the original FlowNet2-pytorch for this task: [/FlowNet2-pytorch](../../FlowNet2-pytorch). You can take a look if you wish.
